### ISSUE TITLE
'Status': does not show properly the muon decay configuration

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#45]
when the muon decay measurement is active (as seen in the bottom row) the status tab still displays Veto: no veto set.   
in the terminal in the background you see that veto is set to channel 3. 

![status](https://cloud.githubusercontent.com/assets/4849214/8034841/f920464c-0deb-11e5-94b0-5db8cfea4003.png)

**Comment by achim1** [comment]
Actually, this is more or less rather a feature than a bug. Or at least not on our side. What the status widget shows, is the information which is in the cpld register of the DAQ card. So the veto ment here, is the "hardware veto" of the card. But we are not using this as it turned out to not work properly. So we implemented our own software-side veto for the muon decay.  However, I agree it should not mislead anyone,  so we could change the label to "Hardware veto"?

**Comment by achim1** [comment]
The status widget lies also in some other point: "Muon rates" appears always under the Active Measurements.
Plus the design of the tab could be improved to make it more appealing

**Comment by hpbretz** [comment]
Currently open files is also not always correct, it doesn't name all files that are implicitly opend by a widget, e.g. the P file when starting a decay measurement. See also https://github.com/achim1/muonic/issues/65

**Comment by caroschwerdt** [comment]
My suggestion: 
Under "settings" > "channel configuration" I would let the label "veto", since all configurations under settings are hardware settings.
Under "muon decay" I would label "veto puls" as "software veto channel".
And then under "status" under "veto" the message "software veto: Channel 3" has to appear.

**Comment by caroschwerdt** [comment]
That muonic is lying under status might have something to do with: muonic was programming at first  that a rate measurement always starts with opening muonic. 
So for me the question is: When is started the R-file to write? By opening muonic or starting a new rate measurement?

**Comment by hpbretz** [comment]
The file is opened when muonic is started. But muonic only writes content to it once a rate measurement is actually started.

**Comment by hpbretz** [comment]
We changed muonic back to always starting a rate measurement, I also added the proposed changes to the status widget.
