### ISSUE TITLE
Start rate measurement together with mu decay measurement

### ISSUE THREAD

**Issue by achim1** [achim1/muonic#51]
If the mu decay measurement is enabled, automatically a rate measurement is started. 
I did not know what the use of this is, so I disabled it for now, can be re-enabled if it was a desired feature.

**Comment by achim1** [comment]
Applies also for the Velocity measurement

**Comment by aschulzdesy** [comment]
Maybe this was planned to get an idea of the stability of the system. Since the rate of decays is low it's easier to check the the behaviour of the detectors using the rates. But no strong opinion on that.

**Comment by hpbretz** [comment]
Sounds reasonable, and I also don't think there's any damage in having a
rate measurement, other than having a bigger output file.

2015-06-22 16:43 GMT+02:00 aschulzdesy notifications@github.com:

**Comment by achim1** [comment]
True, but it somehow circumvents the "Run/Stop Run" mechanism we introduced for the rate measurement. However, if thought to be useful, it should be re-enabled.

**Comment by hpbretz** [comment]
What's the status on this, do we leave it as it is right now?

**Comment by caroschwerdt** [comment]
Ok I understand Achim's point but I'm also Hapes and Annelies opinion.
It's confusing when you start a lifetime or velocity measurement and no rate measurement is displayed. I think a rate measurement is still the precondition for filtering decays in such a rate measurement. That this then runs in the background, is difficult to perceive for students. 
It is also good to have this option in order to check whether the detectors are set correctly, as Annelie wrote.
So please re-enable it and as well as the function that a status line is then written in the R-file.

**Comment by hpbretz** [comment]
Also add comment "new rate/decay/velocity measurement started"

**Comment by hpbretz** [comment]
Fixed in https://github.com/achim1/muonic/commit/74e9ccc289abc818c59cea671dc94347494e167b
