### ISSUE TITLE
Pulsefilenames date format not consistent

### ISSUE THREAD

**Issue by achim1** [achim1/muonic#52]
It seems that the month is written like "6" instead of "06" in the name of the pulsefile

**Comment by aschulzdesy** [comment]
Example here
![bildschirmfoto vom 2015-07-21 10_41_54](https://cloud.githubusercontent.com/assets/4849214/8796464/44922026-2f95-11e5-8447-a6c088974980.png)

**Comment by hpbretz** [comment]
which version of muonic is this?

**Comment by hpbretz** [comment]
Whit the current commit (2.0.15), it should work properly.

**Comment by aschulzdesy** [comment]
Hi, this is not working. See screeshot: 
![bildschirmfoto vom 2015-07-22 10_14_02](https://cloud.githubusercontent.com/assets/4849214/8821018/a792daec-305a-11e5-912c-0e4aecedb3b8.png)

**Comment by hpbretz** [comment]
Managed to reproduce the issue. This happens when one starts muonic without the option '-p', and then activates the pulse analyzer widget. In that case, the starting time of the pulse file is also different from the other file because a different time function (time.gmtime()) is used. I'll change this to use the same defintion at all places.

**Comment by hpbretz** [comment]
Fixed in commit https://github.com/achim1/muonic/commit/04c044f174572faddfb766a113607639ab6da9bb

**Comment by hpbretz** [comment]
test again with newest version. If it is fixed in 2.0.21, we need a new package with 2.0.21, because it doesn't work in 2.0.20

**Comment by hpbretz** [comment]
Works properly in 2.0.22
